//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenteeAssignment.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.IWCFCustomer")]
    public interface IWCFCustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCustomer/getAllCustomer", ReplyAction="http://tempuri.org/IWCFCustomer/getAllCustomerResponse")]
        System.Data.DataTable getAllCustomer(string strWhere, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCustomer/getAllCustomer", ReplyAction="http://tempuri.org/IWCFCustomer/getAllCustomerResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllCustomerAsync(string strWhere, string strOrderBy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCustomerChannel : MenteeAssignment.CustomerService.IWCFCustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFCustomerClient : System.ServiceModel.ClientBase<MenteeAssignment.CustomerService.IWCFCustomer>, MenteeAssignment.CustomerService.IWCFCustomer {
        
        public WCFCustomerClient() {
        }
        
        public WCFCustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFCustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getAllCustomer(string strWhere, string strOrderBy) {
            return base.Channel.getAllCustomer(strWhere, strOrderBy);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllCustomerAsync(string strWhere, string strOrderBy) {
            return base.Channel.getAllCustomerAsync(strWhere, strOrderBy);
        }
    }
}
