//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenteeAssignment.TransactionsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransactionsService.IWCFTransactions")]
    public interface IWCFTransactions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFTransactions/getAllTransaction", ReplyAction="http://tempuri.org/IWCFTransactions/getAllTransactionResponse")]
        System.Data.DataTable getAllTransaction(string strWhere, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFTransactions/getAllTransaction", ReplyAction="http://tempuri.org/IWCFTransactions/getAllTransactionResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAllTransactionAsync(string strWhere, string strOrderBy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFTransactionsChannel : MenteeAssignment.TransactionsService.IWCFTransactions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFTransactionsClient : System.ServiceModel.ClientBase<MenteeAssignment.TransactionsService.IWCFTransactions>, MenteeAssignment.TransactionsService.IWCFTransactions {
        
        public WCFTransactionsClient() {
        }
        
        public WCFTransactionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFTransactionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFTransactionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFTransactionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getAllTransaction(string strWhere, string strOrderBy) {
            return base.Channel.getAllTransaction(strWhere, strOrderBy);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAllTransactionAsync(string strWhere, string strOrderBy) {
            return base.Channel.getAllTransactionAsync(strWhere, strOrderBy);
        }
    }
}
